name: flutter_scandit_plugin
description: Flutter Plugin for Scandit Barcode Scanning on Android and iOS
version: 2.0.0
homepage: https://github.com/fryette/flutter_scandit
repository: https://github.com/fryette/flutter_scandit
issue_tracker: https://github.com/fryette/flutter_scandit/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.ysampir.flutter_scandit_plugin
        pluginClass: FlutterScanditPlugin
      ios:
        pluginClass: SwiftFlutterScanditPlugin
